language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

matrix:
    include:
        - php: 7.2
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'

branches:
    only:
        - master

install:
    - composer install --prefer-source

script:
    - ./bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
